services:
  db:
    image: postgres:16-alpine
    container_name: pt-novo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noticias_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: pt-novo-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3333
      DATABASE_URL: postgresql://postgres:postgres@db:5432/noticias_db?schema=public
    ports:
      - '3333:3333'

volumes:
  postgres_data:
